server:
  port: 9080

##mensageria.rabbitmq.nome-host=10.11.103.10
#mensageria:
#  rabbitmq:
#    nome-host: localhost
#    porta: 5672
#    usuario: guestd
#    senha: guestser
#    timeout: 10000

spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: 0.0.0.0
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
